name: aistack

# Open Webui
services:
  ollama:
    volumes:
      - ./data/ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}
  openwebui:
    image: ghcr.io/open-webui/open-webui:${OPEN_WEBUI_DOCKER_TAG-latest}
    volumes:
      - ./data/open-webui:/app/backend/data
    ports:
      - ${OPEN_WEBUI_PORT-3000}:8080
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
      - 'WEBUI_SECRET_KEY=${OPEN_WEBUI_SECRET_KEY}'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
