name: aistack

# Open Webui
services:
  ollama:
    volumes:
      - ./data/ollama:/root/.ollama
    container_name: ollama
    #pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}
    networks:
      - aistack-net
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility

  openwebui:
    image: ghcr.io/open-webui/open-webui:${OPEN_WEBUI_DOCKER_TAG-latest}
    volumes:
      - ./data/open-webui:/app/backend/data
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
      - 'WEBUI_SECRET_KEY=${OPEN_WEBUI_SECRET_KEY}'
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - USE_CUDA_DOCKER=True
      - ENABLE_RAG_WEB_SEARCH=True
      - RAG_WEB_SEARCH_ENGINE=searxng
      - SEARXNG_QUERY_URL=http://searxng:8080/search?q=<query>
      - ENABLE_CODE_INTERPRETER=True
      - CODE_EXECUTION_ENGINE=jupyter
      - CODE_EXECUTION_JUPYTER_URL=http://jupyter:8888
      - CODE_EXECUTION_JUPYTER_AUTH=token
      - CODE_EXECUTION_JUPYTER_AUTH_TOKEN=${JUPYTER_TOKEN-123456}
      - CODE_EXECUTION_JUPYTER_TIMEOUT=60
      - CODE_INTERPRETER_ENGINE=jupyter
      - CODE_INTERPRETER_JUPYTER_URL=http://jupyter:8888
      - CODE_INTERPRETER_JUPYTER_AUTH=token
      - CODE_INTERPRETER_JUPYTER_AUTH_TOKEN=${JUPYTER_TOKEN-123456}
      - CODE_INTERPRETER_JUPYTER_TIMEOUT=60

    depends_on:
      - ollama
    restart: unless-stopped
    networks:
      - aistack-net
    runtime: nvidia

  caddy:
    image: caddy:alpine
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./container/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./data/caddy:/data
      - ./data/caddy_config:/config
    networks:
      - aistack-net
    restart: unless-stopped
    depends_on:
      - openwebui
      - jupyter

  searxng:
    image: searxng/searxng:${SEARXNG_DOCKER_TAG-latest}
    container_name: searxng
    restart: unless-stopped
    volumes:
      - ./data/searxng:/etc/searxng
    environment:
      - BASE_URL=http://searxng:8080
      - INSTANCE_NAME=searxng-docker
    networks:
      - aistack-net

  jupyter:
    image: jupyter/minimal-notebook:latest
    restart: unless-stopped
    volumes:
      - ./data/jupyter:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN=${JUPYTER_TOKEN-123456}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    networks:
      - aistack-net

  pipelines:
    image: ghcr.io/open-webui/pipelines:main-cuda
    volumes:
      - ./data/pipelines:/app/pipelines
    restart: unless-stopped
    environment:
      - PIPELINES_API_KEY=0p3n-w3bu!
    networks:
      - aistack-net

networks:
  aistack-net:
    driver: bridge
